begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table public.countries (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  flag_url text,
  kind text not null default 'country' check (kind in ('country', 'region', 'international')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint countries_name_key unique (name),
  constraint countries_code_key unique (code)
);

comment on table public.countries is 'Reference catalog for countries and competition regions such as World or Europe.';

create table public.venues (
  id integer primary key,
  name text not null,
  city text,
  capacity integer check (capacity is null or capacity >= 0),
  image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.seasons (
  year integer primary key check (year between 1900 and 2200),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.leagues (
  id integer primary key,
  name text not null,
  type text not null check (type in ('League', 'Cup')),
  country_id bigint references public.countries(id) on delete set null,
  logo_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint leagues_name_country_key unique (name, country_id)
);

create table public.league_seasons (
  league_id integer not null references public.leagues(id) on delete cascade,
  season_year integer not null references public.seasons(year) on delete cascade,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  coverage jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (league_id, season_year),
  constraint league_seasons_date_check check (end_date is null or start_date is null or end_date >= start_date)
);

create table public.teams (
  id integer primary key,
  name text not null,
  code text,
  country_id bigint references public.countries(id) on delete set null,
  founded integer check (founded is null or founded between 1800 and 2100),
  logo_url text,
  venue_id integer references public.venues(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint teams_name_country_key unique (name, country_id)
);

create table public.team_league_seasons (
  team_id integer not null references public.teams(id) on delete cascade,
  league_id integer not null,
  season_year integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (team_id, league_id, season_year),
  constraint team_league_seasons_league_season_fk
    foreign key (league_id, season_year)
    references public.league_seasons(league_id, season_year)
    on delete cascade
);

create table public.players (
  id integer primary key,
  name text not null,
  first_name text,
  last_name text,
  birth_date date check (birth_date is null or birth_date <= current_date),
  nationality_country_id bigint references public.countries(id) on delete set null,
  height_cm smallint check (height_cm is null or height_cm between 100 and 250),
  weight_kg smallint check (weight_kg is null or weight_kg between 30 and 200),
  photo_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

comment on column public.players.birth_date is 'Store birth date instead of age so the data does not drift over time.';

create table public.squads (
  team_id integer not null references public.teams(id) on delete cascade,
  player_id integer not null references public.players(id) on delete cascade,
  season_year integer not null references public.seasons(year) on delete cascade,
  squad_number smallint,
  position text,
  is_active boolean not null default true,
  joined_at date,
  left_at date,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (team_id, player_id, season_year),
  constraint squads_number_check check (squad_number is null or squad_number between 0 and 99),
  constraint squads_dates_check check (left_at is null or joined_at is null or left_at >= joined_at)
);

create table public.fixtures (
  id integer primary key,
  kickoff_at timestamptz not null,
  league_id integer not null,
  season_year integer not null,
  round text,
  home_team_id integer not null references public.teams(id) on delete restrict,
  away_team_id integer not null references public.teams(id) on delete restrict,
  venue_id integer references public.venues(id) on delete set null,
  referee text,
  status_short text not null,
  status_long text,
  status_elapsed smallint check (status_elapsed is null or status_elapsed >= 0),
  last_synced_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint fixtures_league_season_fk
    foreign key (league_id, season_year)
    references public.league_seasons(league_id, season_year)
    on delete restrict,
  constraint fixtures_home_away_check check (home_team_id <> away_team_id)
);

comment on column public.fixtures.status_short is 'Raw API-Football status code such as NS, HT, FT, PST, or CANC.';

create table public.match_analyses (
  id bigint generated by default as identity primary key,
  fixture_id integer not null unique references public.fixtures(id) on delete cascade,
  title text not null,
  excerpt text,
  content_markdown text not null,
  seo_description text,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint match_analyses_publish_state_check check (status <> 'published' or published_at is not null)
);

comment on table public.match_analyses is 'Editorial content per fixture, separate from live score data.';

create index countries_kind_idx on public.countries(kind);
create index venues_city_idx on public.venues(city);
create index leagues_country_idx on public.leagues(country_id);
create unique index league_seasons_one_current_per_league_idx on public.league_seasons(league_id) where is_current;
create index league_seasons_current_idx on public.league_seasons(season_year, is_current) where is_current;
create index teams_country_idx on public.teams(country_id);
create index teams_venue_idx on public.teams(venue_id);
create index team_league_seasons_league_season_idx on public.team_league_seasons(league_id, season_year);
create index players_nationality_idx on public.players(nationality_country_id);
create index squads_team_season_idx on public.squads(team_id, season_year);
create index squads_player_season_idx on public.squads(player_id, season_year);
create index fixtures_kickoff_idx on public.fixtures(kickoff_at);
create index fixtures_league_season_kickoff_idx on public.fixtures(league_id, season_year, kickoff_at desc);
create index fixtures_home_team_kickoff_idx on public.fixtures(home_team_id, kickoff_at desc);
create index fixtures_away_team_kickoff_idx on public.fixtures(away_team_id, kickoff_at desc);
create index fixtures_status_kickoff_idx on public.fixtures(status_short, kickoff_at desc);
create index match_analyses_status_published_idx on public.match_analyses(status, published_at desc);

create trigger countries_set_updated_at
before update on public.countries
for each row execute function public.set_updated_at();

create trigger venues_set_updated_at
before update on public.venues
for each row execute function public.set_updated_at();

create trigger seasons_set_updated_at
before update on public.seasons
for each row execute function public.set_updated_at();

create trigger leagues_set_updated_at
before update on public.leagues
for each row execute function public.set_updated_at();

create trigger league_seasons_set_updated_at
before update on public.league_seasons
for each row execute function public.set_updated_at();

create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

create trigger team_league_seasons_set_updated_at
before update on public.team_league_seasons
for each row execute function public.set_updated_at();

create trigger players_set_updated_at
before update on public.players
for each row execute function public.set_updated_at();

create trigger squads_set_updated_at
before update on public.squads
for each row execute function public.set_updated_at();

create trigger fixtures_set_updated_at
before update on public.fixtures
for each row execute function public.set_updated_at();

create trigger match_analyses_set_updated_at
before update on public.match_analyses
for each row execute function public.set_updated_at();

alter table public.countries enable row level security;
alter table public.venues enable row level security;
alter table public.seasons enable row level security;
alter table public.leagues enable row level security;
alter table public.league_seasons enable row level security;
alter table public.teams enable row level security;
alter table public.team_league_seasons enable row level security;
alter table public.players enable row level security;
alter table public.squads enable row level security;
alter table public.fixtures enable row level security;
alter table public.match_analyses enable row level security;

create policy "public read countries"
on public.countries
for select
using (true);

create policy "public read venues"
on public.venues
for select
using (true);

create policy "public read seasons"
on public.seasons
for select
using (true);

create policy "public read leagues"
on public.leagues
for select
using (true);

create policy "public read league seasons"
on public.league_seasons
for select
using (true);

create policy "public read teams"
on public.teams
for select
using (true);

create policy "public read team league seasons"
on public.team_league_seasons
for select
using (true);

create policy "public read players"
on public.players
for select
using (true);

create policy "public read squads"
on public.squads
for select
using (true);

create policy "public read fixtures"
on public.fixtures
for select
using (true);

create policy "public read published match analyses"
on public.match_analyses
for select
using (status = 'published');

commit;
